name: Deploy Hugo site and push on GCS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo blog
        uses: actions/checkout@v3

      - name: Checkout repo themes
        uses: actions/checkout@v3
        with:
          repository: bcollard/west-side-volley-theme
          path: themes/hugo-scroll
          #token: ${{ secrets.GH_PAT }}
          ssh-key: ${{ secrets.SSH_KEY_THEME }}
          ref: master

      # https://github.com/google-github-actions/setup-gcloud
      - name: 'Auth through GCP Workload Identity Federation'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/681025799424/locations/global/workloadIdentityPools/gitops-pool/providers/gh-provider'
          service_account: 'gha-push-gcs-blog@personal-218506.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.114.0'
          extended: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: install gems
        run: gem install asciidoctor asciidoctor-revealjs rouge asciidoctor-confluence asciidoctor-diagram coderay pygments.rb

      - name: Build the website
        run: hugo --gc

      - name: Push to GCS
        run: gsutil -m rsync -r -d public gs://westsidevolley.net

      - name: Set cache control headers on assets
        shell: bash
        run: |
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*.webp || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*.jpg || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*.png || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*/\*.css || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*/\*.jpg || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*/\*.webp || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*/\*.png || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://westsidevolley.net/\*/\*.js || true

      
